---
- name: Auto-configuration of cjdns' IPTunnel
  hosts: all

  tasks:
  - git: repo=https://github.com/postmodern/ruby-install.git dest=/opt/ruby-install update=no
  - shell: "make && make install chdir=/opt/ruby-install creates=/usr/local/bin/ruby-install"
  - command: ruby-install ruby 2.2.1 creates=/opt/rubies/ruby-2.2.1/bin/ruby

  - git: repo=https://github.com/postmodern/chruby.git dest=/opt/chruby update=no
  - shell: "make && make install chdir=/opt/chruby creates=/usr/local/bin/chruby-exec"
  - file: dest=/etc/profile.d/chruby.sh state=touch mode=0644
  - lineinfile: dest=/etc/profile.d/chruby.sh create=yes line="source /usr/local/share/chruby/chruby.sh"
  - lineinfile: dest=/etc/profile.d/chruby.sh line="chruby 2.2.1"
  - command: chruby-exec 2.2.1 -- gem install bundler --no-rdoc --no-ri creates=/opt/rubies/ruby-2.2.1/bin/bundle
